CREATE TABLE employees (
    id UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(20) UNIQUE NOT NULL,
    position SMALLINT NOT NULL DEFAULT 4 CHECK (position BETWEEN 1 AND 4),
    salary NUMERIC(10, 2) NOT NULL,
    address VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1 CHECK (status BETWEEN 1 AND 2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

CREATE TRIGGER trg_update_employees_updated_at
	BEFORE UPDATE ON employees
	FOR EACH ROW
	EXECUTE FUNCTION update_timestamp();
